HARD_SKILL_KEYWORDS = [
    # Programming languages
    "Python",
    "R",
    "Java",
    "Scala",
    "C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Julia",
    "MATLAB",
    "SAS",
    "Bash",
    "Shell Scripting",
    # Data and ML
    "SQL",
    "NoSQL",
    "Machine Learning",
    "Data Analysis",
    "Data Engineering",
    "Data Modeling",
    "Data Warehousing",
    "Data Visualization",
    "Deep Learning",
    "NLP",
    "Natural Language Processing",
    "Computer Vision",
    "Reinforcement Learning",
    "Generative AI",
    "LLM",
    "RAG",
    "Prompt Engineering",
    "MLOps",
    "Feature Engineering",
    "A/B Testing",
    "Statistical Modeling",
    "Time Series",
    "Recommendation Systems",
    "ETL",
    "ELT",
    "Data Pipeline",
    # ML/AI frameworks
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "XGBoost",
    "LightGBM",
    "Hugging Face",
    "OpenAI",
    "LangChain",
    "LlamaIndex",
    "Transformers",
    "ONNX",
    "MLflow",
    "Kubeflow",
    "Weights and Biases",
    # Data tools
    "Pandas",
    "NumPy",
    "Spark",
    "PySpark",
    "Hadoop",
    "Hive",
    "Kafka",
    "Airflow",
    "dbt",
    "Dagster",
    "Prefect",
    "Dask",
    "Polars",
    # Visualization
    "Tableau",
    "Power BI",
    "Looker",
    "Matplotlib",
    "Plotly",
    "D3.js",
    "Grafana",
    "Excel",
    "Google Sheets",
    # Databases
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "DynamoDB",
    "Cassandra",
    "Neo4j",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Databricks",
    "Pinecone",
    "ChromaDB",
    "Weaviate",
    # Cloud and infrastructure
    "AWS",
    "Azure",
    "GCP",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "CI/CD",
    "GitHub Actions",
    "Jenkins",
    "Linux",
    "Nginx",
    # Web and API
    "FastAPI",
    "Flask",
    "Django",
    "Node.js",
    "Express",
    "Next.js",
    "React",
    "Vue",
    "Angular",
    "REST API",
    "GraphQL",
    "gRPC",
    "Streamlit",
    "Gradio",
    # DevOps and tools
    "Git",
    "Jira",
    "Confluence",
    "Agile",
    "Scrum",
    # Security and compliance
    "OAuth",
    "RBAC",
    "SOC 2",
    "GDPR",
    "HIPAA",
    # Other technical
    "Microservices",
    "Event-Driven Architecture",
    "System Design",
    "API Design",
    "Testing",
    "Unit Testing",
    "Integration Testing",
    "Performance Testing",
    "Playwright",
    "Selenium",
    "Figma",
]

SOFT_SKILL_KEYWORDS = [
    "communication",
    "teamwork",
    "problem-solving",
    "leadership",
    "adaptability",
    "time management",
    "collaboration",
    "critical thinking",
    "stakeholder management",
    "mentoring",
    "cross-functional",
    "project management",
    "decision-making",
    "presentation",
    "negotiation",
    "conflict resolution",
    "strategic thinking",
    "attention to detail",
    "self-motivated",
    "analytical thinking",
    "creative thinking",
    "customer-focused",
    "prioritization",
    "ownership",
    "accountability",
    "empathy",
    "coaching",
    "initiative",
    "resilience",
    "influence",
]
